In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [19]:
import io

In [20]:
from google.colab import files

In [21]:
uploaded = files.upload()

Saving employees_pandas_practice.csv to employees_pandas_practice.csv

In [24]:
df = pd.read_csv(io.BytesIO(uploaded["employees_pandas_practice.csv"]))

In [25]:
df.head(5)

,Employee_ID,Name,Age,Gender,Department,Job_Role,Salary,Experience_Years,City,Joining_Date,Performance_Score,Bonus,Education
0,1,Aditya Sharma,38,Male,Marketing,Marketing Executive,114000,16,Chandigarh,2022-08-19,8.0,NaN,B.Tech
1,2,Tanya Patel,55,Female,Marketing,Marketing Manager,128000,25,Mumbai,2023-11-03,8.0,12800.0,M.Tech
2,3,Akash Joshi,27,Female,Operations,Operations Manager,70000,4,Noida,2017-05-30,8.0,3500.0,MCA
3,4,Varun Patel,25,Male,Marketing,Marketing Manager,59000,3,Chandigarh,2020-04-09,8.0,7080.0,BBA
4,5,Ishaan Gupta,31,Male,Finance,Finance Manager,106000,14,NaN,2018-06-22,8.0,5300.0,B.Com

In [29]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Gender', 'Department', 'Job_Role',
       'Salary', 'Experience_Years', 'City', 'Joining_Date',
       'Performance_Score', 'Bonus', 'Education'],
      dtype='object')

Last ten rows

In [33]:
df.tail(10)

,Employee_ID,Name,Age,Gender,Department,Job_Role,Salary,Experience_Years,City,Joining_Date,Performance_Score,Bonus,Education
90,91,Rahul Khanna,54,Male,Operations,Operations Manager,141000,25,Jaipur,2024-09-11,8.0,NaN,MCA
91,92,Anika Mishra,45,Female,Sales,Sales Executive,129000,25,Gurugram,2023-06-15,7.0,12900.0,MBA
92,93,Yash Gupta,40,Female,Operations,Operations Analyst,117000,18,Noida,2020-01-26,5.0,11700.0,B.Sc
93,94,Esha Mehta,29,Male,HR,HR Manager,74000,7,Noida,2025-05-17,9.0,3700.0,M.Sc
94,95,Chetan Yadav,32,Male,Customer Support,Support Specialist,91000,15,Bengaluru,2020-12-28,10.0,9100.0,BBA
95,96,Karan Ahuja,33,Female,Customer Support,Support Manager,88000,14,Noida,2021-12-04,8.0,7040.0,B.Com
96,97,Ananya Ahuja,44,Male,HR,HR Manager,115000,22,Hyderabad,2021-01-18,9.0,9200.0,B.Sc
97,98,Manish Sharma,47,Male,Data Science,Senior Data Scientist,166000,25,Chandigarh,2020-03-19,7.0,8300.0,MCA
98,99,Chetan Kumar,23,Female,Customer Support,Support Specialist,66000,7,Gurugram,2016-01-26,6.0,3300.0,PhD
99,100,Pooja Singh,39,Male,Sales,Sales Executive,102000,16,Jaipur,2023-03-06,10.0,12240.0,PhD

Number of Rows and Coloumns

In [35]:
df.shape

(100, 13)

In [38]:
nds = df[['Name','Department','Salary']]

In [39]:
nds

             Name        Department  Salary
0   Aditya Sharma         Marketing  114000
1     Tanya Patel         Marketing  128000
2     Akash Joshi        Operations   70000
3     Varun Patel         Marketing   59000
4    Ishaan Gupta           Finance  106000
..            ...               ...     ...
95    Karan Ahuja  Customer Support   88000
96   Ananya Ahuja                HR  115000
97  Manish Sharma      Data Science  166000
98   Chetan Kumar  Customer Support   66000
99    Pooja Singh             Sales  102000

[100 rows x 3 columns]

Displaying result for Employee_ID == 105

In [43]:
df[df['Employee_ID']==105]

Empty DataFrame
Columns: [Employee_ID, Name, Age, Gender, Department, Job_Role, Salary, Experience_Years, City, Joining_Date, Performance_Score, Bonus, Education]
Index: []